CREATE TABLESPACE Exemple_TS 
datafile 'Exemple_TS.dbf'
SIZE 20M;

CREATE TEMPORARY TABLESPACE Temp_nas
TEMPFILE 'temp01.dbf' SIZE 5M;

CREATE PROFILE app_user LIMIT
SESSIONS_PER_USER UNLIMITED
CPU_PER_SESSION UNLIMITED
CPU_PER_CALL 3000
CONNECT_TIME 45
LOGICAL_READS_PER_SESSION DEFAULT
LOGICAL_READS_PER_CALL 1000
PRIVATE_SGA 15K
COMPOSITE_LIMIT 5000000;


CREATE USER Michael
IDENTIFIED BY "mBi?_odo16"
DEFAULT TABLESPACE Exemple_TS
QUOTA 10M ON Exemple_TS
TEMPORARY TABLESPACE Temp_nas
QUOTA 5M ON system
PROFILE app_user
PASSWORD EXPIRE;


