--------------------------------------------------------
--  File created - Tuesday-November-01-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CHAUFFEUR
--------------------------------------------------------

  CREATE TABLE "MAHERY"."CHAUFFEUR" 
   (	"NUMCHAUFF" NUMBER(*,0), 
	"NOMCHAUFF" VARCHAR2(30 BYTE), 
	"CIN" VARCHAR2(20 BYTE), 
	"NUMTEL" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIGRATION" ;
--------------------------------------------------------
--  DDL for Table LIGNE
--------------------------------------------------------

  CREATE TABLE "MAHERY"."LIGNE" 
   (	"NUMLIGNE" NUMBER(*,0), 
	"NOMLIGNE" VARCHAR2(60 BYTE), 
	"DISTANCE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIGRATION" ;
--------------------------------------------------------
--  DDL for Table VEHICULE
--------------------------------------------------------

  CREATE TABLE "MAHERY"."VEHICULE" 
   (	"NUMVEHICULE" NUMBER(*,0), 
	"NUMCHAUFFEUR" NUMBER(*,0), 
	"TYPE_VOITURE" VARCHAR2(20 BYTE), 
	"COULEUR" VARCHAR2(20 BYTE), 
	"PUISSANCE" VARCHAR2(10 BYTE), 
	"IMMATRICULATION" VARCHAR2(10 BYTE), 
	"LIGNE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIGRATION" ;
REM INSERTING into MAHERY.CHAUFFEUR
SET DEFINE OFF;
REM INSERTING into MAHERY.LIGNE
SET DEFINE OFF;
REM INSERTING into MAHERY.VEHICULE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_CHAUFFEUR
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAHERY"."PK_CHAUFFEUR" ON "MAHERY"."CHAUFFEUR" ("NUMCHAUFF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIGRATION" ;
--------------------------------------------------------
--  DDL for Index PK_LIGNE
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAHERY"."PK_LIGNE" ON "MAHERY"."LIGNE" ("NUMLIGNE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIGRATION" ;
--------------------------------------------------------
--  DDL for Index PK_VEHICULE
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAHERY"."PK_VEHICULE" ON "MAHERY"."VEHICULE" ("NUMVEHICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIGRATION" ;
--------------------------------------------------------
--  DDL for Index SYS_C007070
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAHERY"."SYS_C007070" ON "MAHERY"."CHAUFFEUR" ("NOMCHAUFF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIGRATION" ;
--------------------------------------------------------
--  DDL for Index SYS_C007078
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAHERY"."SYS_C007078" ON "MAHERY"."VEHICULE" ("IMMATRICULATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIGRATION" ;
--------------------------------------------------------
--  DDL for Index PK_CHAUFFEUR
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAHERY"."PK_CHAUFFEUR" ON "MAHERY"."CHAUFFEUR" ("NUMCHAUFF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIGRATION" ;
--------------------------------------------------------
--  DDL for Index SYS_C007070
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAHERY"."SYS_C007070" ON "MAHERY"."CHAUFFEUR" ("NOMCHAUFF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIGRATION" ;
--------------------------------------------------------
--  DDL for Index PK_LIGNE
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAHERY"."PK_LIGNE" ON "MAHERY"."LIGNE" ("NUMLIGNE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIGRATION" ;
--------------------------------------------------------
--  DDL for Index PK_VEHICULE
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAHERY"."PK_VEHICULE" ON "MAHERY"."VEHICULE" ("NUMVEHICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIGRATION" ;
--------------------------------------------------------
--  DDL for Index SYS_C007078
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAHERY"."SYS_C007078" ON "MAHERY"."VEHICULE" ("IMMATRICULATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIGRATION" ;
--------------------------------------------------------
--  Constraints for Table CHAUFFEUR
--------------------------------------------------------

  ALTER TABLE "MAHERY"."CHAUFFEUR" ADD UNIQUE ("NOMCHAUFF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIGRATION"  ENABLE;
  ALTER TABLE "MAHERY"."CHAUFFEUR" ADD CONSTRAINT "PK_CHAUFFEUR" PRIMARY KEY ("NUMCHAUFF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIGRATION"  ENABLE;
  ALTER TABLE "MAHERY"."CHAUFFEUR" MODIFY ("NUMCHAUFF" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LIGNE
--------------------------------------------------------

  ALTER TABLE "MAHERY"."LIGNE" ADD CONSTRAINT "PK_LIGNE" PRIMARY KEY ("NUMLIGNE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIGRATION"  ENABLE;
  ALTER TABLE "MAHERY"."LIGNE" MODIFY ("NUMLIGNE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VEHICULE
--------------------------------------------------------

  ALTER TABLE "MAHERY"."VEHICULE" ADD UNIQUE ("IMMATRICULATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIGRATION"  ENABLE;
  ALTER TABLE "MAHERY"."VEHICULE" ADD CONSTRAINT "PK_VEHICULE" PRIMARY KEY ("NUMVEHICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIGRATION"  ENABLE;
  ALTER TABLE "MAHERY"."VEHICULE" ADD CONSTRAINT "CK_PUISSANCE" CHECK (Puissance >= 0) ENABLE;
  ALTER TABLE "MAHERY"."VEHICULE" MODIFY ("LIGNE" NOT NULL ENABLE);
  ALTER TABLE "MAHERY"."VEHICULE" MODIFY ("NUMCHAUFFEUR" NOT NULL ENABLE);
  ALTER TABLE "MAHERY"."VEHICULE" MODIFY ("NUMVEHICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table VEHICULE
--------------------------------------------------------

  ALTER TABLE "MAHERY"."VEHICULE" ADD CONSTRAINT "FK_CHAUFFEUR" FOREIGN KEY ("NUMCHAUFFEUR")
	  REFERENCES "MAHERY"."CHAUFFEUR" ("NUMCHAUFF") ENABLE;
  ALTER TABLE "MAHERY"."VEHICULE" ADD CONSTRAINT "FK_LIGNE" FOREIGN KEY ("LIGNE")
	  REFERENCES "MAHERY"."LIGNE" ("NUMLIGNE") ENABLE;
